### ISSUE TITLE
Add site header and footer

### ISSUE THREAD

**Issue by stefanha** [FederationOfTech/Coalesce#67]
MainLayout.vue has a header that simply says "Coalesce". The UI wireframe shows a navigation bar in the header and a footer with copyright information and links.

Add these to MainLayout.vue so that every page has a standard header/footer as shown in the UI wireframe.

See #43 for the UI wireframe and details of what should be in the header and footer.

**Comment by kavitakapoor** [comment]
The header. 

The link will be 

Home takes you to the index.html page  [#66] 
About and Contact  takes you to a new website [Federationof.tech ](https://www.federationof.tech/humanitarian-software)
Opportunities and the magnifying glass icon take you to the Search Opportunities page  - [#28]  
"Sign Up" [takes you to the /organisers/create](http://localhost:8080/#/organisers/create) 

![Nav Bar](https://user-images.githubusercontent.com/8677451/141806716-505fa00f-36ed-453e-a122-51ddd289a3b3.png)
