### ISSUE TITLE
Make frontend URLs and filenames consistent

### ISSUE THREAD

**Issue by stefanha** [FederationOfTech/Coalesce#72]
Frontend URLs (/organizer vs /create-organiser) and filenames
(CreateOrganiser.vue vs CreateAnOpportunity.vue) are inconsistent in
spelling and structure. It was difficult to achieve consistency during
the April Hackathon with people working in parallel.

**Comment by timrog** [comment]
https://github.com/FederationOfTech/Coalesce/pull/75
