### ISSUE TITLE
Create opportunity detail API endpoint

### ISSUE THREAD

**Issue by Nolski** [FederationOfTech/Coalesce#8]
**Associated with the Opportunity Detail Epic #3**
We will want to create an API endpoint which will give detailed information on an opportunity by ID

The API endpoint should provide the following information on a single opportunity
 - Title
 - Current status
 - Skills required
 - Organizer photo
 - Opportunity description
 - Personnel needed
 - Commitment type
 - Date of event
 - Location

**Comment by stefanha** [comment]
The REST API implements this:
`http://localhost:8080/api/v1/opportunities/<id>/`
